# Generated by Django 6.0.4 on 2026-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('preparation_steps', models.TextField()),
                ('calories', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('diet_type', models.CharField(choices=[('keto', 'Keto Friendly'), ('vegan', 'Vegan / Vegetarian'), ('protein', 'High Protein'), ('gluten-free', 'Gluten-Free')], max_length=20)),
                ('image', models.ImageField(upload_to='healthy_photos/')),
            ],
        ),
    ]
