# Generated by Django 6.0.4 on 2026-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_delete_healthyrecipe_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(default=500, help_text='Calories per serving'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet_type',
            field=models.CharField(choices=[('all', 'All Recipes'), ('keto', 'Keto Friendly'), ('vegan', 'Vegan / Vegetarian'), ('protein', 'High Protein'), ('gluten-free', 'Gluten-Free')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=30, help_text='Preparation time in minutes'),
        ),
    ]
